In [1]:
import os
import csv
import pandas as pd
import numpy as np
import matplotlib

In [2]:
land_data = os.path.join("county ppsf sales data csv.csv")

In [3]:
land_df = pd.read_csv(land_data)
land_df.head()

  Month of Period End           Region  Avg. Median Ppsf   County
0              17-Dec   Union City, CA        516.663062  Alameda
1              18-Jan   Union City, CA        519.561665  Alameda
2              18-Feb   Union City, CA        555.555556  Alameda
3              17-Dec  San Leandro, CA        458.887381  Alameda
4              18-Jan  San Leandro, CA        454.341737  Alameda

In [4]:
# Are we missing any data for given cities? - No
land_df.count()

Month of Period End    195
Region                 195
Avg. Median Ppsf       195
County                 195
dtype: int64

In [5]:
land_df.columns

Index(['Month of Period End', 'Region', 'Avg. Median Ppsf', 'County'], dtype='object')

In [6]:
grouped_land_data = land_df.groupby(["Region"])
grouped_land_data.head(1)

    Month of Period End             Region  Avg. Median Ppsf        County
0                17-Dec     Union City, CA        516.663062       Alameda
3                17-Dec    San Leandro, CA        458.887381       Alameda
6                17-Dec     Pleasanton, CA        547.799617       Alameda
9                17-Dec        Oakland, CA        509.960159       Alameda
12               17-Dec         Newark, CA        553.523680       Alameda
15               17-Dec      Livermore, CA        461.880772       Alameda
18               17-Dec        Hayward, CA        442.088037       Alameda
21               17-Dec        Fremont, CA        622.365571       Alameda
24               17-Dec         Dublin, CA        483.789260       Alameda
27               17-Dec       Berkeley, CA        687.764011       Alameda
30               17-Dec        Alameda, CA        585.585586       Alameda
33               17-Dec   Walnut Creek, CA        448.314396  Contra Costa
36               17-Dec      San Ramon, CA        494.210555  Contra Costa
39               17-Dec      San Pablo, CA        319.685254  Contra Costa
42               17-Dec       Richmond, CA        391.730605  Contra Costa
45               17-Dec  Pleasant Hill, CA        454.660188  Contra Costa
48               17-Dec      Pittsburg, CA        254.913639  Contra Costa
51               17-Dec         Pinole, CA        360.000000  Contra Costa
54               17-Dec         Orinda, CA        488.789108  Contra Costa
57               17-Dec         Oakley, CA        240.872211  Contra Costa
60               17-Dec       Martinez, CA        375.375032  Contra Costa
63               17-Dec      Lafayette, CA        527.889048  Contra Costa
66               17-Dec       Hercules, CA        331.038136  Contra Costa
69               17-Dec       Danville, CA        503.835510  Contra Costa
72               17-Dec        Concord, CA        375.894988  Contra Costa
75               17-Dec      Brentwood, CA        252.138903  Contra Costa
78               17-Dec        Antioch, CA        236.302521  Contra Costa
81               17-Dec     San Rafael, CA        560.639199         Marin
84               17-Dec         Novato, CA        456.323338         Marin
87               17-Dec    Mill Valley, CA        726.718559         Marin
..                  ...                ...               ...           ...
105              17-Dec     San Carlos, CA        970.902130     San Mateo
108              17-Dec      San Bruno, CA        693.641618     San Mateo
111              17-Dec   Redwood City, CA        985.532465     San Mateo
114              17-Dec       Pacifica, CA        665.277778     San Mateo
117              17-Dec     Menlo Park, CA       1321.591886     San Mateo
120              17-Dec    Foster City, CA        831.455061     San Mateo
123              17-Dec      Daly City, CA        664.658634     San Mateo
126              17-Dec     Burlingame, CA       1170.559596     San Mateo
129              17-Dec        Belmont, CA        925.132915     San Mateo
132              17-Dec      Sunnyvale, CA       1126.577146   Santa Clara
135              17-Dec       Saratoga, CA       1036.268738   Santa Clara
138              17-Dec    Santa Clara, CA        871.602624   Santa Clara
141              17-Dec       San Jose, CA        635.982586   Santa Clara
144              17-Dec      Palo Alto, CA       1346.331769   Santa Clara
147              17-Dec  Mountain View, CA       1057.827927   Santa Clara
150              17-Dec    Morgan Hill, CA        411.874332   Santa Clara
153              17-Dec       Milpitas, CA        641.058925   Santa Clara
156              17-Dec      Los Gatos, CA        804.640719   Santa Clara
159              17-Dec      Los Altos, CA       1271.739130   Santa Clara
162              17-Dec         Gilroy, CA        352.807971   Santa Clara
165              17-Dec      Cupertino, CA       1232.960961   Santa Clara
168              17-Dec       Campbell, CA        789.931431   Santa Clara
171              17-Dec        Vallejo, CA        266.707921        Solano
174              17-Dec      Vacaville, CA        250.900901        Solano
177              17-Dec    Suisun City, CA        237.811791        Solano
180              17-Dec      Fairfield, CA        235.426009        Solano
183              17-Dec        Benicia, CA        312.752968        Solano
186              17-Dec         Sonoma, CA        519.400353        Sonoma
189              17-Dec     Santa Rosa, CA        383.858791        Sonoma
192              17-Dec   Rohnert Park, CA        345.619665        Sonoma

[65 rows x 4 columns]

In [7]:
# This is the mean of the Avg Median.PPSF
avg_price = grouped_land_data.mean()
avg_price.head()

                     Avg. Median Ppsf
Region
Alameda, CA                574.329990
American Canyon, CA        284.420696
Antioch, CA                237.773274
Belmont, CA                918.636961
Benicia, CA                336.423543

In [8]:
avg_price = avg_price.reset_index()
avg_price.head()

                Region  Avg. Median Ppsf
0          Alameda, CA        574.329990
1  American Canyon, CA        284.420696
2          Antioch, CA        237.773274
3          Belmont, CA        918.636961
4          Benicia, CA        336.423543

In [9]:
#rename the average price column
df = avg_price.rename(columns={'Avg. Median Ppsf': 'Average_price'})
df.head()

                Region  Average_price
0          Alameda, CA     574.329990
1  American Canyon, CA     284.420696
2          Antioch, CA     237.773274
3          Belmont, CA     918.636961
4          Benicia, CA     336.423543

In [14]:
#now we will add a new column that contains that state name for all cities (in case we need this for the API call)
len(df.index)

65

In [15]:
state = []
for x in range(len(df.index)):
    state.append('CA')

In [17]:
df['State'] = state
df.head()

                Region  Average_price State
0          Alameda, CA     574.329990    CA
1  American Canyon, CA     284.420696    CA
2          Antioch, CA     237.773274    CA
3          Belmont, CA     918.636961    CA
4          Benicia, CA     336.423543    CA